on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: MichaelVoelkel/lintly-flake8-github-action@v1.1
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Additional arguments to pass to flake8, default "." (current directory)
          args: "--ignore=E121,E123 ."
          # post linter failures as comments and not change requests
          requestChanges: "True"

